id: pii
version: 0.9.0
title: PII Redaction
subtitle: Keep your data secure
buttonText: Let's go
steps:
  - id: "0"
    title: "Step 1: Finish setup"
    subSteps:
      - id: 0-a
        title: Update the SmartHub
        content:
          - items:
              - text: |
                  While you can see the initial MDAI cluster has already been set up, there are some final steps of setup that are worth covering in detail.
              - text: |
                  We'll declare some variables in our SmartHub that will define how the sensitive data is handled.
              - text: |
                  Note that these variables are manual, defined on <button:0>line 14</button> and <button:1>line 23</button>. This indicates that <emphasize>you</emphasize> will be managing them, the SmartHub will not update manual variables.
                actions:
                  - kind: "scroll_to"
                    waitForComplete: false
                    simulator: "config"
                    updates:
                      fileName: hub-single-var.yaml
                      line: 14
                      scrollOnly: true
                  - kind: "scroll_to"
                    waitForComplete: false
                    simulator: "config"
                    updates:
                      fileName: hub-single-var.yaml
                      line: 23
                      scrollOnly: true
        initialState:
          config:
            files:
              - url: "https://github.com/MyDecisive/mdai-labs/blob/2ed0b992468072e44917739755f5bc4a34517840/0.9.0/use_cases/pii/dynamic/hub-single-var.yaml"
                fileName: hub-single-var.yaml
                changes:
                  - start: 11
                    end: 18
                    changeLines: []
                  - start: 20
                    end: 27
                    changeLines: []
          status:
            - namespace: mdai
              name: prometheus-kube-prometheus-stack-prometheus-0
              noSuffix: true
            - namespace: mdai
              name: opentelemetry-operator-744c8c4b5
            - namespace: mdai
              name: mdai-valkey-primary-0
              noSuffix: true
            - namespace: mdai
              name: mdai-prometheus-node-exporter
            - namespace: mdai
              name: mdai-operator-controller-manager-554b6b7cb8
            - namespace: mdai
              name: mdai-nats-box-6d8bb549dc
            - namespace: mdai
              name: mdai-nats-2
              noSuffix: true
            - namespace: mdai
              name: mdai-nats-1
              noSuffix: true
            - namespace: mdai
              name: mdai-nats-0
              noSuffix: true
            - namespace: mdai
              name: mdai-kube-state-metrics-6d4ddf5f7
            - namespace: mdai
              name: mdai-grafana-895587c5b
            - namespace: mdai
              name: mdai-gateway-58bc5d4c59
            - namespace: mdai
              name: mdai-event-hub-5bb5477dcf
            - namespace: mdai
              name: kube-prometheus-stack-operator-58f649f96d
            - namespace: mdai
              name: alertmanager-kube-prometheus-stack-alertmanager-0
              noSuffix: true
        animation:
          - kind: "enter_command"
            simulator: "terminal"
            updates:
              - input: "mdai apply ./0.9.0/use_cases/pii/dynamic/hub-single-var.yaml"
                outputs:
                  - "✅ Prerequisites OK"
                  - "+ kubectl  apply -f ./0.9.0/use_cases/pii/dynamic/hub-single-var.yaml -n mdai"
                  - "Warning: no `PrometheusAlerts` provided; MdaiHub will not setup alerts"
                  - "Warning: no `Rules` provided; MdaiHub will perform no actions"
                  - "mdaihub.hub.mydecisive.ai/mdaihub-pii created"
          - kind: "stream"
            simulator: "logs"
            updates:
              contextName: mdai-operator-controller-manager-554b6b7cb8
              fileName: piiRedactSmartHubUpdate.txt
              logFormat: json
              speed: 300
              duration: 4200
      - id: 0-b
        title: Spin up a collector
        content:
          - items:
              - text: |
                  This collector config has a transform processor declared on <button:0>line 42</button> that makes use of the SmartHub <button:1>manual variables</button> that were declared in the previous step.
                actions:
                  - kind: "scroll_to"
                    waitForComplete: false
                    simulator: "config"
                    updates:
                      fileName: otel-single-var.yaml
                      line: 42
                      scrollOnly: true
                  - kind: "scroll_to"
                    waitForComplete: false
                    simulator: "config"
                    updates:
                      fileName: otel-single-var.yaml
                      line: 48
                      scrollOnly: true
        initialState:
          config:
            files:
              - url: "https://github.com/MyDecisive/mdai-labs/blob/2ed0b992468072e44917739755f5bc4a34517840/0.9.0/use_cases/pii/dynamic/otel-single-var.yaml"
                fileName: otel-single-var.yaml
                changes:
                  - start: 42
                    end: 48
                    changeLines: []
                  - start: 72
                    end: 72
                    changeLines: []
            activeTab: otel-single-var.yaml
        animation:
          - kind: "enter_command"
            simulator: "terminal"
            updates:
              - input: "mdai apply ./0.9.0/use_cases/pii/dynamic/otel-single-var.yaml"
                outputs:
                  - "✅ Prerequisites OK"
                  - "+ kubectl  apply -f ./0.9.0/use_cases/pii/dynamic/otel-single-var.yaml -n mdai"
                  - "opentelemetrycollector.opentelemetry.io/gateway created"
          - kind: "add_services"
            simulator: "status"
            updates:
              - name: gateway-collector-84888ddfc7
                namespace: mdai
          - kind: "stream"
            simulator: "logs"
            updates:
              contextName: gateway-collector-84888ddfc7
              fileName: piiRedactCollectorStart.txt
              logFormat: collector
              speed: 100
              duration: 2400
      - id: 0-c
        title: Send some data
        content:
          - items:
              - text: |
                  Now that we have a SmartHub and collector up, let's send some data.
        animation:
          - kind: "enter_command"
            simulator: "terminal"
            updates:
              - input: "mdai apply ./mock-data/pii.yaml"
                outputs:
                  - "✅ Prerequisites OK"
                  - "+ kubectl  apply -f ./mock-data/pii.yaml -n mdai"
                  - "configmap/fluentd-v2 created"
                  - "deployment.apps/fluentd created"
          - kind: "add_services"
            simulator: "status"
            updates:
              - name: fluentd-9fcdf85dc
                namespace: mdai
          - kind: "stream"
            simulator: "logs"
            updates:
              contextName: gateway-collector-84888ddfc7
              fileName: piiRedactCollectorInitialData.txt
              logFormat: multiline
              speed: 150
              duration: 3000
  - id: "1"
    title: "Step 2: Perform redaction"
    subSteps:
      - id: 1-a
        title: Update manual variables
        content:
          - items:
              - text: |
                  The <emphasize>mdai-gateway</emphasize> service is the entry point to the SmartHub for just about any operation you want to execute against the running cluster.

                  As such, one method to update manual variables is via curl request.
          - items:
              - text: |
                  In order to send a curl to the <emphasize>mdai-gateway</emphasize>, we first need to forward its port.
              - text: <code>kubectl port-forward -n mdai svc/mdai-gateway 8081:8081</code>
          - items:
              - text: |
                  After that, we can send our OTTL compatible regex and get our variables updated!
        animation:
          - kind: "enter_command"
            simulator: "terminal"
            updates:
              - input: |
                  curl -sS -X POST \
                    -H 'Content-Type: application/json' \
                    -d \"$(printf '{\"data\":\"%s\"}' \"$transformed_cc_str\")\" \
                    'http://localhost:8081/variables/hub/mdaihub-pii/var/cc_regex'"
                outputs:
                  - |
                    {"id":"019be7b6-ad58-7e39-8c2d-129bec0c1083","name":"var.add","version":1,"timestamp":"2026-01-22T21:57:47.480933346Z","payload":"{\"variableRef\":\"cc_regex\",\"dataType\":\"string\",\"operation\":\"add\",\"data\":\"\\\\\\\\b(?:\\\\\\\\d[ -]*){11,15}(\\\\\\\\d{4})\\\\\\\\b\"}","source":"manual_variables_api","source_id":"","hub_name":"mdaihub-pii"}
          - kind: "enter_command"
            simulator: "terminal"
            updates:
              - input: |
                  curl -sS -X POST \
                    -H 'Content-Type: application/json' \
                    -d '{\"data\":\"********-****-****-$1\"}' \
                    'http://localhost:8081/variables/hub/mdaihub-pii/var/cc_template'"
                outputs:
                  - |
                    {"id":"019be7b7-6a34-73e6-8f39-fc202df63fac","name":"var.add","version":1,"timestamp":"2026-01-22T21:58:35.828256341Z","payload":"{\"variableRef\":\"cc_template\",\"dataType\":\"string\",\"operation\":\"add\",\"data\":\"********-****-****-$1\"}","source":"manual_variables_api","source_id":"","hub_name":"mdaihub-pii"}
          - kind: "stream"
            simulator: "logs"
            updates:
              contextName: gateway-collector-84888ddfc7
              fileName: piiRedactCollectorRedactedCCData.txt
              logFormat: multiline
              speed: 100
              duration: 2400
