name: Deploy Site

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment?
        options: 
          - Staging
          - Prod
      rusure:
        type: choice
        description: Are you sure?
        options: 
          - "no"
          - "no?"
          - "no."
          - "no!"
          - "yes"
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check for Production Environment
        if: github.event.inputs.environment == 'Prod'
        run: |
          echo "PROD? THERE IS NO PROD HERE."
          exit 1
